"""Port of `com.t4login.definitions.priceconversion.IMarketConversion`.

Expressed as a `typing.Protocol` (structural subtyping) rather than a Java
interface. Merges `IPriceFormatArgs` into this single Protocol since Java's
`IMarketConversion extends IPriceFormatArgs`.

Yield-related optional getters are included for completeness but typed as
returning `None` by default (most chartdata implementors don't populate them).
"""

from __future__ import annotations

from decimal import Decimal
from typing import Protocol

from t4login.definitions.priceconversion.price import Price
from t4login.definitions.priceconversion.vpt import VPT


class IMarketConversion(Protocol):
    """Structural interface for market price conversion parameters."""

    def get_market_id(self) -> str: ...
    def get_denominator(self) -> int: ...
    def get_price_code(self) -> str: ...
    def get_min_price_increment(self) -> Price: ...
    def get_vpt(self) -> VPT | None: ...
    def get_min_cab_price(self) -> Price | None: ...
    def get_real_decimals(self) -> int: ...
    def get_clearing_decimals(self) -> int: ...
    def get_point_value(self) -> Decimal: ...

    # Yield-related (optional — may return None)
    def get_yield_years(self) -> int | None: ...
    def get_yield_par_value(self) -> float | None: ...
    def get_yield_rate(self) -> float | None: ...
    def get_yield_value_denominator(self) -> int | None: ...
    def get_yield_redemption(self) -> float | None: ...
    def get_yield_payments_per_year(self) -> float | None: ...
    def get_yield_basis(self) -> int | None: ...
